version: "3.2"
services: 
  react-app:
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment: 

      env_file: 
         ./.env