version: "3.2"
services: 
  react-app:
      # stdin_open: true
      # tty: true
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/app/src
    environment: 
      - REACT_APP_NAME=Yaniv
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   -  ./.env